#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2023 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 0.23.0
# Product:       sfx6xxx
# Model-Version: 2.0.0
#

import pytest
import time
from sensirion_uart_sfx6xxx.device import Sfx6xxxDevice


@pytest.fixture
def sensor(channel_provider):
    # Create Channel
    with channel_provider:
        channel = channel_provider.get_channel(0.05)
        dev = Sfx6xxxDevice(channel)
        yield dev


def test_get_serial_number1(sensor):
    serial_number = sensor.get_serial_number()
    print(f"serial_number: {serial_number}; "
          )


def test_device_reset1(sensor):
    sensor.device_reset()


def test_close_valve1(sensor):
    sensor.close_valve()


def test_set_setpoint1(sensor):
    sensor.set_setpoint(2)
    averaged_measured_value = sensor.read_averaged_measured_value(50)
    print(f"averaged_measured_value: {averaged_measured_value}; "
          )
    sensor.close_valve()

