#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2022 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:    sensirion-driver-generator 0.17.0
# Product:      sfc6xxx
# Version:      1.0
#

import pytest
import time
from sensirion_shdlc_driver import ShdlcSerialPort

from sensirion_driver_adapters.shdlc_adapter.shdlc_channel import ShdlcChannel
from sensirion_uart_sfc6xxx.device import Sfc6xxxDevice


@pytest.fixture
def sensor(shdlc_port):
    # Create Channel
    channel = ShdlcChannel(shdlc_port)
    dev = Sfc6xxxDevice(channel)
    time.sleep(0.1)  # some time is required to power up the device
    yield dev


@pytest.mark.needs_device
def test_get_serial_number1(sensor):
    serial_number = sensor.get_serial_number()
    print(f"serial_number: {serial_number}; "
          )


@pytest.mark.needs_device
def test_device_reset1(sensor):
    sensor.device_reset()


@pytest.mark.needs_device
def test_close_valve1(sensor):
    sensor.close_valve()


@pytest.mark.needs_device
def test_set_setpoint1(sensor):
    sensor.set_setpoint(1, 2)
    measured_value = sensor.read_measured_value(1)
    print(f"measured_value: {measured_value}; "
          )
    sensor.close_valve()

